apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helabooking-ingress
  namespace: default
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: staging.helabooking.com # Placeholder host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helabooking-service
                port:
                  number: 80
