apiVersion: v1
kind: Service
metadata:
  name: helabooking-service
  namespace: default
  labels:
    app: helabooking
spec:
  selector:
    app: helabooking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
